In [14]:
# weight update test
import numpy
import scipy.special

#시그모이드 함수
activation_function = lambda x: scipy.special.expit(x)

#입력->은닉계층 가중치
W_ih = numpy.array([[3.0, 2.0],[1.0, 7.0]])
print("W_ih\n", W_ih)

#은닉->출력계층 가중치
W_ho = numpy.array([[2.0, 3.0],[1.0, 4.0]])
print("W_ho\n", W_ho)

#은닉계층 출력값 (책에서 주어진 값임.)
O_hidden =  numpy.array([0.4, 0.5],ndmin=2).T
print("O_hidden\n", O_hidden)


####은닉계층 입력값 찾는과정######
#시그모이드함수의 역함수
#inverse_function = lambda x: (-1) * numpy.log((1.0/x) -1) #직접계산해서 만든 역함수
#(scipy.special.logit() #제공하는 시그모이드함수의 역함수

#은닉계층 입력값 계산 
#( 은닉계층입력값 -> (시그모이드 함수) -> 은닉계층출력값)
#( 은닉계층입력값 <- (시그모이드 역함수 <- 은닉계층출력값)

print("시그모이드 함수의 역함수를 통해 은닉 계층의 입력값 계산")
#X_hidden = inverse_function(O_hidden)

X_hidden_1=scipy.special.logit(0.4)
X_hidden_2=scipy.special.logit(0.5)
X_hidden=numpy.array([X_hidden_1, X_hidden_2],ndmin=2).T
print(X_hidden)

# W_ih*I= X_hidden
# I = W_ih의 역행렬 * X_hidden

print("W_ih가중치 행렬의 역행렬")
# 제공하는 W_ih역행렬 구하는 함수: numpy.linalg.inv(W_ih)
print("inv(W_ih) :",numpy.linalg.inv(W_ih))

# 입력배열
print("W_ih가중치행렬의 역행렬과 은닉계층의입력값(X_hidden) 곱해서 입력 배열 구하기")
inputs = numpy.dot(numpy.linalg.inv(W_ih), X_hidden)
print("입력배열\n",inputs)

#입력배열 inputs=numpy.matrix([[-0.14938188,[0.02134027]]) 나올것임.
inputs=numpy.array([-0.14938188, 0.02134027],ndmin=2).T
print("입력배열.T\n",inputs)

#출력계층 오차 (책에서 주어진 값임.)
output_errors = numpy.array([0.8, 0.5],ndmin=2).T
print("출력계층 오차\n", output_errors)

###출력계층 오차의 총합### -> 은닉계층 오차의 총합과 비교하기 위해서 계산함
print("출력계층 오차의 총합(은닉계층의 오차총합과 비교해볼것!!)\n", sum(output_errors))

#은닉->출력계층가중치 총합(각 행값을 더해줌)  (역전파할때 가중치를 정규화하기 위해 필요함)
W_ho_sum1 = W_ho.sum(axis=1, dtype='float')
print("W_ho 가중치 총합\n", W_ho_sum1)

#은닉->출력계층 정규화된 가중치
W_ho_norm = W_ho/W_ho_sum1
print("W_ho 정규화된 가중치\n", W_ho_norm)

#역전파된 은닉계층 오차
hidden_errors = numpy.dot(W_ho_norm.T, output_errors)
print("역전파된 hidden_error\n", hidden_errors)

###은닉계층 오차의 총합### -> 출력계층 오차의 총합과 비교해봐!!
print("은닉계층 오차의 총합, 출력계층 오차의 총합과비교해보기!!!\n", sum(hidden_errors))

#WjkOj는 즉, 출력계층 입력값(X_output)임. (은닉계층출력값(O_hidden)d이랑 W_ho 곱한거)
WjkOj = numpy.dot(W_ho, O_hidden)
print("WjkOj (즉, X_output)\n", WjkOj)

#S는 위 값에 시그모이드 함수를 적용한것. 즉 출력계층 출력값(O_output).
S = activation_function(WjkOj)
print("WjkOj에 시그모이드함수 적용한것 (즉, O_output) S\n", S)

#가중치 업데이트를 위해 필요한값. S1S = S*(1-S)
S1S =  numpy.multiply(S, (1.0 - S))
print("S1S\n", S1S)

# 우리가 여태 구하려던 '오차기울기'
delEoverdelWjk = - numpy.dot((output_errors*S1S), O_hidden.T)
print("우리가 여태 구하려던 오차기울기 delEoverdelWjk\n", delEoverdelWjk)

#최종 업데이트된 가중치 W_ho
lr=0.1 #학습률
W_ho = W_ho - (lr*delEoverdelWjk)
print("최종 업데이트된 가중치W_ho !!!!\n", W_ho)


# WijOi 는 은닉계층입력값 (X_hidden)임. (inputs 값이랑 W_ij 곱한거)
WijOi = numpy.dot(W_ih, inputs)
print("WijOi (즉, X_hidden)\n", WijOi)

#S는 위값에 시그모이드 함수를 적용한것. 즉 은닉계층 출력값(O_hidden).
#S = O_hidden
S=activation_function(WijOi)
print("WijOi에 시그모이드함수 적용한것 (즉, O_hidden) S\n", S)

#가중치 업데이트를 위해 필요한값. S1S = S*(1-S)
S1S =  numpy.multiply(S, (1.0 -S))
print("S1S\n", S1S)

# 우리가 여태 구하려던 '오차기울기' 
delEoverdelWij = - numpy.dot((hidden_errors*S1S), inputs.T)
print("우리가 여태 구하려던 오차기울기 delEoverdelWij\n", delEoverdelWij)

#최종 업데이트된 가중치 W_ih
W_ih = W_ih - (lr*delEoverdelWij)
print("최종 업데이트된 가중치W_ih !!!!!\n", W_ih)




#########################################################################

# 입력->은닉계층 가중치총합 (역전파할때 가중치를 정규화하기 위해 필요함)
#W_ih_sum1 = W_ih.sum(axis=1, dtype='float')
#print("Winput_hidden_sum1\n", W_ih_sum1)

#입력->은닉계층 정규화된 가중치
#W_ih_norm = W_ih/W_ih_sum1
#print("Winput_output_norm\n", W_ih_norm)

#역전파된 입력계층 오차
#input_errors = numpy.dot(W_ih_norm.T, hidden_errors)
#print("Einput\n", input_errors)

#입력계층 오차의 총합
#print("Einput_sum\n", sum(input_errors))
##### 출력계층오차총합, 은닉계층오차총합, 입력계층오차총합 다 같다. 정규화했기때문에!






















W_ih
 [[3. 2.]
 [1. 7.]]
W_ho
 [[2. 3.]
 [1. 4.]]
O_hidden
 [[0.4]
 [0.5]]
시그모이드 함수의 역함수를 통해 은닉 계층의 입력값 계산
[[-0.40546511]
 [ 0.        ]]
W_ih가중치 행렬의 역행렬
inv(W_ih) : [[ 0.36842105 -0.10526316]
 [-0.05263158  0.15789474]]
W_ih가중치행렬의 역행렬과 은닉계층의입력값(X_hidden) 곱해서 입력 배열 구하기
입력배열
 [[-0.14938188]
 [ 0.02134027]]
입력배열.T
 [[-0.14938188]
 [ 0.02134027]]
출력계층 오차
 [[0.8]
 [0.5]]
출력계층 오차의 총합(은닉계층의 오차총합과 비교해볼것!!)
 [1.3]
W_ho 가중치 총합
 [5. 5.]
W_ho 정규화된 가중치
 [[0.4 0.6]
 [0.2 0.8]]
역전파된 hidden_error
 [[0.42]
 [0.88]]
은닉계층 오차의 총합, 출력계층 오차의 총합과비교해보기!!!
 [1.3]
WjkOj (즉, X_output)
 [[2.3]
 [2.4]]
WjkOj에 시그모이드함수 적용한것 (즉, O_output) S
 [[0.90887704]
 [0.9168273 ]]
S1S
 [[0.08281957]
 [0.076255  ]]
우리가 여태 구하려던 오차기울기 delEoverdelWjk
 [[-0.02650226 -0.03312783]
 [-0.015251   -0.01906375]]
최종 업데이트된 가중치W_ho !!!!
 [[2.00265023 3.00331278]
 [1.0015251  4.00190637]]
WijOi (즉, X_hidden)
 [[-4.054651e-01]
 [ 1.000000e-08]]
WijOi에 시그모이드함수 적용한것 (즉, O_hidden) S
 [[0.4]
 [0.5]]
S1S
 [[0.24]
 [0.25]]
우리가 여태 구하려던 오차기울기 delEove